In [33]:
import numpy as np
import cv2
import matplotlib.pyplot as plt

In [34]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

In [35]:
my_faces = np.load('my_faces.npy')
unknown_faces = np.load('unknown_faces.npy')

In [36]:
data = np.r_[my_faces.reshape(400,-1), unknown_faces.reshape(400,-1)]

In [37]:
# Normalisation

data = data / 255.0

In [38]:
data.shape

(800, 7500)

In [39]:
data.shape[0],1

(800, 1)

In [40]:
labels = np.zeros((data.shape[0],1))

In [41]:
labels.shape

(800, 1)

In [42]:
labels[400:,0] = 1.0

In [43]:
np.unique(labels, return_counts=True)

(array([0., 1.]), array([400, 400], dtype=int64))

In [44]:
names = {
    0 : 'Kashish',
    1 : 'Unknown'
    
}

In [45]:
labels.shape

(800, 1)

In [46]:
labels[:10]

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [75]:
# Train_Test_Splitting

x_train , x_test , y_train , y_test = train_test_split(data, labels, test_size=0.20)

In [76]:
x_train.shape , x_test.shape , y_train.shape , y_test.shape

((640, 7500), (160, 7500), (640, 1), (160, 1))

In [77]:
y_train[:10]

array([[1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.]])

In [78]:
logistic = LogisticRegression()
logistic.fit(x_train,y_train.flatten())

LogisticRegression()

In [79]:
y_pred = logistic.predict(x_test)


In [80]:
accuracy_score(y_test, y_pred)

1.0

In [81]:
knn = KNeighborsClassifier()
knn.fit(x_train, y_train.flatten())

KNeighborsClassifier()

In [82]:
y_pred_knn = knn.predict(x_test)

In [83]:
accuracy_score(y_test, y_pred_knn)

1.0

In [84]:
haardata = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

#cap = cv2.VideoCapture(0)
cap = cv2.VideoCapture('videoplayback.wmv')
faceData = []
font = cv2.FONT_HERSHEY_COMPLEX
while True:
    flag, img = cap.read()
    if flag:
        #img = cv2.resize(img, None, fx=0.5, fy=0.5)
        faces = haardata.detectMultiScale(img,1.2)
        for x,y,w,h in faces:
            cv2.rectangle(img, (x,y), (x+w, y+h), (0,0,255), 5)
            face = img[y:y+h, x:x+w, :]
            face = cv2.resize(face, (50,50))
            face = face / 255.0
            pred = logistic.predict(face.reshape(1,-1))
            name = names[int(pred)]
            #print(pred)
            cv2.putText(img, name, (x,y), font, 1, (0,255,0),1)
        cv2.imshow('img', img)
        if cv2.waitKey(1) == 27 or len(faceData) >= 400:
            break
    else:
        print("Camera is not detected...")
        break
cv2.destroyAllWindows()
cap.release()

In [64]:
from sklearn.metrics import confusion_matrix

In [65]:
confusion_matrix(y_test, y_pred)

array([[100,   0],
       [  0, 100]], dtype=int64)