In [50]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder , OneHotEncoder , StandardScaler

In [51]:
df = pd.read_csv('Madedata1.csv')

In [52]:
df.shape

(2499, 12)

In [53]:
df.head()

Country  Age       Gender  fever  Bodypain  Runny_nose  \
0               China   10         Male    102         1           0   
1               Italy   20         Male    103         1           1   
2                Iran   55  Transgender     99         0           0   
3  Republic of Korean   37       Female    100         0           1   
4              France   45         Male    101         1           1   

   Difficulty_in_breathing  Nasal_congestion  Sore_throat  Severity  \
0                        0                 0            1      Mild   
1                        0                 0            0  Moderate   
2                        0                 1            1    Severe   
3                        1                 0            0      Mild   
4                        1                 1            0  Moderate   

  Contact_with_covid_patient  Infected  
0                         No         0  
1                  Not known         1  
2                         No         0  
3                        Yes         1  
4                        Yes         1

In [54]:
df.drop(columns=['Country'] ,inplace=True)

In [55]:
df.shape

(2499, 11)

In [56]:
 df['Gender'].unique()

array(['Male', 'Transgender', 'Female'], dtype=object)

In [57]:
df['Severity'].unique()

array(['Mild', 'Moderate', 'Severe'], dtype=object)

In [58]:
 df['Contact_with_covid_patient'].unique()

array(['No', 'Not known', 'Yes', 'yes'], dtype=object)

In [59]:
   df['Contact_with_covid_patient'] = df['Contact_with_covid_patient'].str.lower()

In [60]:
 df['Contact_with_covid_patient'].unique()

array(['no', 'not known', 'yes'], dtype=object)

In [61]:
gender = df['Gender'].values
severity = df['Severity'].values
contact = df['Contact_with_covid_patient'].values

In [62]:
df.drop(columns=['Gender', 'Severity', 'Contact_with_covid_patient'],inplace=True)

In [63]:
gender_label = LabelEncoder()
gender = gender_label.fit_transform(gender)

In [64]:
gender

array([1, 1, 2, ..., 0, 0, 0])

In [65]:
gender_onehot = OneHotEncoder()

In [66]:
gender_onehot.fit_transform(gender.reshape(-1,1)).toarray()

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       ...,
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [67]:
gender = gender_onehot.fit_transform(gender.reshape(-1,1)).toarray()

In [75]:
severity_label = LabelEncoder()
severity = severity_label.fit_transform(severity)

severity_onehot = OneHotEncoder()
severity = severity_onehot.fit_transform(severity.reshape(-1,1)).toarray()

In [76]:
contact_label = LabelEncoder()
contact = contact_label.fit_transform(contact)

contact_onehot = OneHotEncoder()
contact = contact_onehot.fit_transform(contact.reshape(-1,1)).toarray()

In [77]:
gender

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       ...,
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [78]:
contact

array([[1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       ...,
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [79]:
severity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       ...,
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])

In [80]:
x = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [81]:
x[0]   #except last colum all are here

array([ 10, 102,   1,   0,   0,   0,   1], dtype=int64)

In [82]:
y[0]   #only the last column

0

In [83]:
x = np.c_[x,gender,severity,contact]

In [84]:
x

array([[ 10., 102.,   1., ...,   1.,   0.,   0.],
       [ 20., 103.,   1., ...,   0.,   1.,   0.],
       [ 55.,  99.,   0., ...,   1.,   0.,   0.],
       ...,
       [ 18.,  99.,   1., ...,   0.,   0.,   1.],
       [ 39., 100.,   1., ...,   0.,   1.,   0.],
       [ 55., 102.,   1., ...,   0.,   0.,   1.]])

In [85]:
x[0]

array([ 10., 102.,   1.,   0.,   0.,   0.,   1.,   0.,   1.,   0.,   1.,
         0.,   0.,   1.,   0.,   0.])

In [86]:
st = StandardScaler()
x = st.fit_transform(x)

In [87]:
from sklearn.model_selection import train_test_split

In [88]:
x.shape

(2499, 16)

In [96]:
 # Whenver we will execute this code , it will always suffle the data
#x_train , x_test, y_train, y_test = train_test_split(x,y,test_size=0.25)

#  if we dont want to shuffle the data then pass random state

x_train , x_test, y_train, y_test = train_test_split(x,y,test_size=0.25,random_state=10)

In [97]:
x_train.shape

(1874, 16)

In [98]:
x_test.shape    #train_test_split  divide the data
                 # 75% in training and 25% in testing

(625, 16)

In [99]:
y_train.shape

(1874,)

In [100]:
y_test.shape

(625,)

In [101]:
from sklearn.linear_model import LogisticRegression

In [102]:
logistic = LogisticRegression()

In [103]:
logistic.fit(x_train,y_train)

LogisticRegression()

In [104]:
y_pred = logistic.predict(x_test)

In [106]:
from sklearn.metrics import accuracy_score

In [107]:
accuracy_score(y_test,y_pred)

0.9456

In [108]:
 #confusion matrix
    
from sklearn.metrics import confusion_matrix

In [109]:
confusion_matrix(y_test,y_pred)

array([[290,  23],
       [ 11, 301]], dtype=int64)

In [110]:
# Accuracy 

(290 + 301) / 625

0.9456

In [111]:
from sklearn.metrics import precision_score,recall_score,accuracy_score,f1_score

In [112]:
precision_score(y_test,y_pred)

0.9290123456790124

In [113]:
recall_score(y_test,y_pred)

0.9647435897435898

In [114]:
accuracy_score(y_test,y_pred)

0.9456

In [115]:
f1_score(y_test,y_pred)

0.9465408805031447

In [116]:
from sklearn.metrics import classification_report

In [119]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.96      0.93      0.94       313
           1       0.93      0.96      0.95       312

    accuracy                           0.95       625
   macro avg       0.95      0.95      0.95       625
weighted avg       0.95      0.95      0.95       625

