In [109]:
import pandas as pd
import urllib.request as url
import matplotlib.pyplot as plt
import numpy as np
import json
plt.style.use('ggplot')

In [110]:
res = url.urlopen('https://api.covid19india.org/states_daily.json')

In [111]:
data = json.load(res)

In [112]:
states = data['states_daily']

In [113]:
df = pd.DataFrame(states)

In [114]:
df.shape

(1473, 42)

In [115]:
confirmed_df = df[df['status'] == 'Confirmed']

In [116]:
total_cases = confirmed_df['tt']

In [117]:
total_cases[:5]

0     81
3     27
6     15
9     11
12    37
Name: tt, dtype: object

In [118]:
total_cases[1:5]

3     27
6     15
9     11
12    37
Name: tt, dtype: object

In [119]:
x = []
y = []

for i in range (len(total_cases)-4):
    x.append(total_cases[i:i+4])
    y.append(total_cases.iloc[i+4])
    

In [120]:
x[0]

0    81
3    27
6    15
9    11
Name: tt, dtype: object

In [121]:
x[1]

3     27
6     15
9     11
12    37
Name: tt, dtype: object

In [122]:
x[2]

6     15
9     11
12    37
15    27
Name: tt, dtype: object

In [123]:
x

[0    81
 3    27
 6    15
 9    11
 Name: tt, dtype: object,
 3     27
 6     15
 9     11
 12    37
 Name: tt, dtype: object,
 6     15
 9     11
 12    37
 15    27
 Name: tt, dtype: object,
 9     11
 12    37
 15    27
 18    58
 Name: tt, dtype: object,
 12    37
 15    27
 18    58
 21    78
 Name: tt, dtype: object,
 15    27
 18    58
 21    78
 24    67
 Name: tt, dtype: object,
 18     58
 21     78
 24     67
 27    102
 Name: tt, dtype: object,
 21     78
 24     67
 27    102
 30     64
 Name: tt, dtype: object,
 24     67
 27    102
 30     64
 33     90
 Name: tt, dtype: object,
 27    102
 30     64
 33     90
 36     65
 Name: tt, dtype: object,
 30     64
 33     90
 36     65
 39    164
 Name: tt, dtype: object,
 33     90
 36     65
 39    164
 42    143
 Name: tt, dtype: object,
 36     65
 39    164
 42    143
 45    110
 Name: tt, dtype: object,
 39    164
 42    143
 45    110
 48    187
 Name: tt, dtype: object,
 42    143
 45    110
 48    187
 51    309
 Nam

In [124]:
n = len(x)
x0 = np.ones(n)

In [125]:
x0

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

In [126]:
x = np.c_[x0, x]

In [127]:
x

array([[1.0, '81', '27', '15', '11'],
       [1.0, '27', '15', '11', '37'],
       [1.0, '15', '11', '37', '27'],
       ...,
       [1.0, '37654', '30818', '40314', '41759'],
       [1.0, '30818', '40314', '41759', '39071'],
       [1.0, '40314', '41759', '39071', '38115']], dtype=object)

In [128]:
x[0]

array([1.0, '81', '27', '15', '11'], dtype=object)

In [129]:
x.shape[1]  

5

In [130]:
x.shape[0] 

487

In [131]:
n

487

In [132]:
from sklearn.preprocessing import MinMaxScaler

In [142]:
mimmax = MinMaxScaler()
scaled_x = np.array.mimmax.fit_transform(x)
scaled_y = np.array.mimmax.fit_transform(y)

AttributeError: 'builtin_function_or_method' object has no attribute 'mimmax'