In [3]:
import sys, time
import numpy as np

In [5]:
np.array([4,3,5,8,5])

array([4, 3, 5, 8, 5])

In [6]:
np.array([4,5,6,7,8.6,20,33])

array([ 4. ,  5. ,  6. ,  7. ,  8.6, 20. , 33. ])

In [7]:
np.array([4,5,6,8,9,7,'hello'])

array(['4', '5', '6', '8', '9', '7', 'hello'], dtype='<U11')

# List v/s Numpy Array


In [8]:
# Space Complexity

list_1 = list()

In [9]:
sys.getsizeof(list_1)

56

In [10]:
arr_1 = np.array([])
sys.getsizeof(arr_1)

104

In [11]:
list_1 = [3,4]
sys.getsizeof(list_1)

72

In [12]:
arr_1 = np.array([3,4])
sys.getsizeof(arr_1)

112

In [13]:
list_1 = list(range(1,1000))
sys.getsizeof(list_1)

8048

In [14]:
arr_1 = np.array([list_1])
sys.getsizeof(arr_1)

4116

In [15]:
# Time Complexity

In [20]:
list_1  = list(range(1,10000000))
list_2  = list(range(1,10000000))
list_3  = []

start = time.time()

for i in range(len(list_1)):
    list_3.append(list_1[i] + list_2[i])
    
end = time.time()
total = end - start
print("Total Time Taken: ",total)

Total Time Taken:  1.8844819068908691


In [23]:
array_1  = np.array(list_1)
array_2  = np.array(list_2)

start = time.time()

array_3  = array_1 + array_2

    
end = time.time()
total = end - start
print("Total Time Taken: ",total)

Total Time Taken:  0.02393817901611328


In [24]:
list_1 = list(range(1,10))

In [25]:
list_1

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [26]:
np.array(list_1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])