In [6]:
import numpy as np

### Things in Numpy
### 1. ways to Create Array
### 2. Slicing of Arrays
### 3. Methods of Arrays

# Ways to Create Array

In [7]:
# 1st Way
np.array([3,4,6,33,55,33,55])

array([ 3,  4,  6, 33, 55, 33, 55])

In [8]:
# 2nd Way
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(10,0,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [10]:
# 3rd Way
# Liner Space
np.linspace(1,10)   #by default iy will return 50 elements in given range

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [11]:
np.linspace(1,10,num= 20)  # it will return 20 elements in given range

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [12]:
np.linspace(1, 10, num= 20, retstep = True)

(array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
         3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
         5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
         8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ]),
 0.47368421052631576)

In [13]:
# 4th Way

np.empty([2,2])

array([[2.12199579e-314, 1.01007000e-311],
       [5.01970696e-321, 1.01007000e-311]])

In [14]:
# 5th Way
np.empty([3,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [15]:
# 6th Way
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
# 7th Way
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
#8th Way
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
np.identity(5) * 6

array([[6., 0., 0., 0., 0.],
       [0., 6., 0., 0., 0.],
       [0., 0., 6., 0., 0.],
       [0., 0., 0., 6., 0.],
       [0., 0., 0., 0., 6.]])

In [19]:
np.random.random()  # by default it will return a value btw 0 and 1

0.8794948124346228

In [20]:
np.random.random(4)

array([0.14885442, 0.68102493, 0.78230365, 0.88758602])

In [21]:
np.random.random([4,4])

array([[0.77488938, 0.86146282, 0.30335237, 0.944768  ],
       [0.94514206, 0.42982562, 0.80276334, 0.97698297],
       [0.10229369, 0.2364127 , 0.1970782 , 0.67416736],
       [0.64572321, 0.06069377, 0.5567633 , 0.49621148]])

In [22]:
np.random.random([4,4]) * 5

array([[2.05293338, 2.54108733, 1.14814851, 1.21398723],
       [4.68416021, 1.03882926, 2.48874272, 0.8401962 ],
       [1.76853346, 1.21476221, 2.76048166, 1.1938628 ],
       [0.41655818, 3.31969178, 2.95757868, 4.05747393]])

In [23]:
#random integer
np.random.randint(10,100)

17

In [24]:
np.random.randint(10,100,10)

array([71, 41, 57, 22, 44, 43, 41, 14, 26, 69])

In [25]:
np.random.randint(10,100,[4,4])

array([[45, 16, 63, 63],
       [67, 22, 42, 78],
       [70, 44, 61, 54],
       [29, 84, 63, 91]])

In [26]:
np.random.randn(3,4)  #zero centred values

array([[-0.59520617,  0.48824341, -0.48118663,  1.03131604],
       [-1.00668528,  0.69445529, -0.37360315,  1.458344  ],
       [ 1.11922575,  0.47689295,  1.39085622,  0.25019652]])

In [27]:
#np.mean(np.random.randn(3,4))

# Slicing of Array


In [28]:
#1-D Array
x = np.random.randint(1,100,15)

In [29]:
x

array([24, 29, 38, 49, 92, 44, 38, 65, 12, 78, 67, 47, 99, 51, 93])

In [30]:
x[0]

24

In [31]:
x[0:4]

array([24, 29, 38, 49])

In [32]:
x[-1]

93

In [33]:
# 2-D Array

x = np.random.randint(1,100,(5,5))

In [34]:
x

array([[58, 81, 22, 92, 12],
       [10, 67,  7, 40, 22],
       [41,  9, 42, 41, 12],
       [77,  2, 45, 41, 51],
       [53, 58,  7, 61, 60]])

In [35]:
x.ndim  #Dimension check

2

In [36]:
x.shape  #shape check

(5, 5)

In [37]:
x[0]   #it will return Row Wise Data

array([58, 81, 22, 92, 12])

In [38]:
x[1]

array([10, 67,  7, 40, 22])

In [39]:
x[0][1]  #now it will return the element

81

In [40]:
x[2][-1]

12

In [41]:
x[:]

array([[58, 81, 22, 92, 12],
       [10, 67,  7, 40, 22],
       [41,  9, 42, 41, 12],
       [77,  2, 45, 41, 51],
       [53, 58,  7, 61, 60]])

In [42]:
x[:,0]

array([58, 10, 41, 77, 53])

In [43]:
x[0:,1]

array([81, 67,  9,  2, 58])

In [44]:
x[0:,1:3]

array([[81, 22],
       [67,  7],
       [ 9, 42],
       [ 2, 45],
       [58,  7]])

In [45]:
x[2:4 , 2:4]

array([[42, 41],
       [45, 41]])

In [46]:
x[:,0:1]

array([[58],
       [10],
       [41],
       [77],
       [53]])

# Methods of Array


In [47]:
len(dir(np))

606

In [48]:
x = np.random.randint(1,100,15)

In [49]:
x

array([38,  1,  4, 36, 73, 26, 83, 59, 79, 16, 71,  2, 67, 23, 93])

In [50]:
np.min(x)

1

In [51]:
np.max(x)

93

In [52]:
np.sort(x)

array([ 1,  2,  4, 16, 23, 26, 36, 38, 59, 67, 71, 73, 79, 83, 93])

In [53]:
np.argmin(x)

1

In [54]:
np.argmax(x)

14

In [55]:
np.argsort(x)

array([ 1, 11,  2,  9, 13,  5,  3,  0,  7, 12, 10,  4,  8,  6, 14],
      dtype=int64)

In [56]:
np.mean(x)

44.733333333333334

In [57]:
np.median(x)

38.0

In [58]:
np.std(x)

30.90300237121881

In [59]:
np.quantile(x,0.5)

38.0

In [60]:
x.shape

(15,)

In [61]:
x.reshape((5,3))

array([[38,  1,  4],
       [36, 73, 26],
       [83, 59, 79],
       [16, 71,  2],
       [67, 23, 93]])

In [62]:
x = x.reshape((5,3))

In [63]:
# Tranpose

x.T

array([[38, 36, 83, 16, 67],
       [ 1, 73, 59, 71, 23],
       [ 4, 26, 79,  2, 93]])

In [64]:
np.mean(x)

44.733333333333334

In [65]:
# Column Wise

np.mean(x,0)

array([48. , 45.4, 40.8])

In [66]:
# Row Wise

np.mean(x,1)

array([14.33333333, 45.        , 73.66666667, 29.66666667, 61.        ])

In [67]:
np.median(x,1)

array([ 4., 36., 79., 16., 67.])

In [68]:
np.std(x,1)

array([16.77961726, 20.2155056 , 10.49867717, 29.78067979, 28.89059824])

In [69]:
# convert data to 1-D

x.flatten()

array([38,  1,  4, 36, 73, 26, 83, 59, 79, 16, 71,  2, 67, 23, 93])

In [70]:
x.reshape(5,-1)  # -1 means 3 by default

array([[38,  1,  4],
       [36, 73, 26],
       [83, 59, 79],
       [16, 71,  2],
       [67, 23, 93]])

In [71]:
x.reshape(-1,5)

array([[38,  1,  4, 36, 73],
       [26, 83, 59, 79, 16],
       [71,  2, 67, 23, 93]])

In [72]:
x.shape

(5, 3)

In [74]:
np.r_[x, [[10,20,30]]]  # adding row 

array([[38,  1,  4],
       [36, 73, 26],
       [83, 59, 79],
       [16, 71,  2],
       [67, 23, 93],
       [10, 20, 30]])

In [78]:
np.c_[x, [[101],[201],[301],[501],[601]]] #adding a column

array([[ 38,   1,   4, 101],
       [ 36,  73,  26, 201],
       [ 83,  59,  79, 301],
       [ 16,  71,   2, 501],
       [ 67,  23,  93, 601]])