In [1]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier

In [2]:
df = pd.read_csv('Madedata1.csv')

In [3]:
df.head()

Country  Age       Gender  fever  Bodypain  Runny_nose  \
0               China   10         Male    102         1           0   
1               Italy   20         Male    103         1           1   
2                Iran   55  Transgender     99         0           0   
3  Republic of Korean   37       Female    100         0           1   
4              France   45         Male    101         1           1   

   Difficulty_in_breathing  Nasal_congestion  Sore_throat  Severity  \
0                        0                 0            1      Mild   
1                        0                 0            0  Moderate   
2                        0                 1            1    Severe   
3                        1                 0            0      Mild   
4                        1                 1            0  Moderate   

  Contact_with_covid_patient  Infected  
0                         No         0  
1                  Not known         1  
2                         No         0  
3                        Yes         1  
4                        Yes         1

In [4]:
df.drop(columns=['Country'] ,inplace=True)

In [5]:
df.shape

(2499, 11)

In [6]:
df.head()

Age       Gender  fever  Bodypain  Runny_nose  Difficulty_in_breathing  \
0   10         Male    102         1           0                        0   
1   20         Male    103         1           1                        0   
2   55  Transgender     99         0           0                        0   
3   37       Female    100         0           1                        1   
4   45         Male    101         1           1                        1   

   Nasal_congestion  Sore_throat  Severity Contact_with_covid_patient  \
0                 0            1      Mild                         No   
1                 0            0  Moderate                  Not known   
2                 1            1    Severe                         No   
3                 0            0      Mild                        Yes   
4                 1            0  Moderate                        Yes   

   Infected  
0         0  
1         1  
2         0  
3         1  
4         1

In [7]:
df['Contact_with_covid_patient'] = df['Contact_with_covid_patient'].str.lower()

In [8]:
gender = df['Gender'].values
severity = df['Severity'].values
contact = df['Contact_with_covid_patient'].values

In [9]:
df.drop(columns=['Gender', 'Severity', 'Contact_with_covid_patient'],inplace=True)

In [10]:
from sklearn.preprocessing import LabelEncoder , OneHotEncoder , StandardScaler

In [11]:
gender_label = LabelEncoder()
gender = gender_label.fit_transform(gender)
gender_onehot = OneHotEncoder()
gender = gender_onehot.fit_transform(gender.reshape(-1,1)).toarray()

In [12]:
severity_label = LabelEncoder()
severity = severity_label.fit_transform(severity)

severity_onehot = OneHotEncoder()
severity = severity_onehot.fit_transform(severity.reshape(-1,1)).toarray()


contact_label = LabelEncoder()
contact = contact_label.fit_transform(contact)

contact_onehot = OneHotEncoder()
contact = contact_onehot.fit_transform(contact.reshape(-1,1)).toarray()

In [13]:
gender

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       ...,
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [14]:
severity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       ...,
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])

In [15]:
contact

array([[1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       ...,
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
x = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [17]:
x

array([[ 10, 102,   1, ...,   0,   0,   1],
       [ 20, 103,   1, ...,   0,   0,   0],
       [ 55,  99,   0, ...,   0,   1,   1],
       ...,
       [ 18,  99,   1, ...,   0,   1,   1],
       [ 39, 100,   1, ...,   1,   0,   0],
       [ 55, 102,   1, ...,   1,   1,   0]], dtype=int64)

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.75)

In [20]:
dt = DecisionTreeClassifier(criterion="entropy")
dt.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy')

In [21]:
y_pred = dt.predict(x_test)

In [22]:
from sklearn.metrics import accuracy_score

In [23]:
accuracy_score(y_test, y_pred)

0.9029333333333334

In [24]:
from IPython.display import Image
from six import StringIO
import pydotplus
from sklearn import tree

In [25]:
dot = StringIO()
features = list(df.columns[:-1])
tree.export_graphviz(dt, out_file=dot, feature_names=features)
graph = pydotplus.graph_from_dot_data(dot.getvalue())

graph.write_png("tree_2.png")

True